version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  app:
    build:
      context: ./brackr-api
    container_name: brackr-app
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./brackr-api:/usr/src/app
    networks:
      - backend
    command: npm run dev
    ports:
      - "3000:3000"

volumes:
  rabbitmq_data:
  redis_data:

networks:
  backend:
    driver: bridge
